### ISSUE TITLE
Restless Mulberry Manatee - Missing input validation in `mint` and `burn` function

### ISSUE THREAD

**Issue by sherlock-admin** [testing-org-1234/2023-08-sentiment-judging#3]
Restless Mulberry Manatee

high

# Missing input validation in `mint` and `burn` function

krkba
## Vulnerability Detail
There is no input validation in `mint` and `burn` function.
## Impact
It's possible to burn more tokens than a user has or mint an excessively large number of tokens.
## Code Snippet
https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/WrappedAvail.sol#L30-L37
## Tool used

Manual Review

## Recommendation
Add checks to prevent these scenarios.

**Comment by rcstanciu** [comment]
asdasdasd

**Comment by rcstanciu** [comment]
The protocol team fixed this issue in PR/commit https://github.com/testing-org-1234/2023-08-sentiment-judging/issues/2.

**Comment by rcstanciu** [comment]
The protocol team fixed this issue in PR/commit https://github.com/testing-org-1234/2023-08-sentiment-judging/issues/1.

**Comment by rcstanciu** [comment]
The Lead Senior Watson signed-off on the fix.

**Comment by rcstanciu** [comment]
The protocol team fixed this issue in PR/commit https://github.com/testing-org-1234/2023-08-sentiment-judging/issues/1.

**Comment by rcstanciu** [comment]
The Lead Senior Watson signed-off on the fix.
